version: '3.9'
services:
  frontend_web:
    image: react-selenium-frontend:latest
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "3000:80"
    environment:
      - "NGINX_PORT=80"
    networks:
      - frontend-network
networks:
  frontend-network:
    name: react_selenium_network